receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4317  # você pode trocar para 4318 se quiser

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  extensions: [zpages]
